### ISSUE TITLE
Bad main entry point in package.json

### ISSUE THREAD

**Issue by Finrod927** [NickMcBurney/storybook-vue3-router#1]
Hi Nick

When using storyshot during unit tests, I got this error message
> Unexpected error while loading ./components/XXX.ts: Error: Cannot find module 'storybook-vue3-router' from 'XXX.ts'

I looked into the `package.json` file and saw that the main entry point is `"main": "dist/cjs/index.js"` but there are no folders `cjs` in the `dist` folder!

Using `"main": "dist/esm/index.js"` solves the issue.

Can you update the package? Thanks :)

_Also, there is a `console.log` left in [withVueRouter](https://github.com/NickMcBurney/storybook-vue3-router/blob/main/src/withVueRouter.ts#L16) ;)_

**Comment by NickMcBurney** [comment]
Hi @Finrod927 thanks for raising an issue! I've fixed the entry point (and removed my debugging console.log 😂) and published a new version 1.0.2
