### ISSUE TITLE
Suggestions to make library more useful

### ISSUE THREAD

**Issue by misha** [NickMcBurney/storybook-vue3-router#15]
In its current state, this library is missing some key features to make it useful in my projects.

1. I need to be able to change route parameters, query parameters, and meta based on story arguments.
2. I need to be able to specify a different route and/or routes for each story within a single story file.

Any ideas on how to tackle these?

**Comment by NickMcBurney** [comment]
Hi @misha, thanks for the feedback.

Point 1: Do you mean through Storybook controller args? or just through setup (static values)? - It won't currently work through args, but I think there is no reason this couldn't be added - though I think it will require a page reload in order to apply.

Point 2: this is possible if you're using the latest v2+ version of the package (have a look at README - its more detailed than previous version) - it possible in v1.

Do you have any code you can share so I can see examples of how you're trying to use it?

**Comment by misha** [comment]
Basically, I want to be able to:

1. Specify a control in `argTypes`.
2. Compute something in `setup` using the current arguments.
3. Pass that value to the current route s.t. calls to `useRoute` and `useRouter` from `vueuse` can read it.

A page reload would be totally acceptable - I believe Storybook already refreshes the story whenever a controlled argument changes, anyway.

**Comment by NickMcBurney** [comment]
@misha, I've created a new PR with new [example](https://github.com/NickMcBurney/storybook-vue3-router/blob/4ef07eaebac5220660e35b69cb05ad4aa69f8bfd/examples/withArgs.stories.ts), can you let me know if this is the kind of thing you're trying to do? (Apologies not sure I've fully understood)

you can also preview my example Storybook [demo site](https://deploy-preview-16--storybook-vue3-router.netlify.app/?path=/story/with-args--default).

If I've misunderstood, please provide a code example so I can better understand your use-case.

**Comment by NickMcBurney** [comment]
@misha any update on this? I'll close issue if I don't hear back from you.

**Comment by misha** [comment]
(Sorry for the delay, had a different task for a while.)

---

In the example code, router data is passed using a prop - but components generally want to access $router and $route for information, and this is indeed what `useRoute` and `useRouter` do. What I'm really looking for is to set $router and/or $route for a particular story.

The solution is probably _not_ a component - it's a utility function or a hook that instruments the router context for that story alone.

Here's the ideal usage:

```vue
<template>
  <div>
    <template v-if="$route.meta.new">
      Welcome!
    <template v-else>
      Welcome back!
    </template>
  </div>
</template>
```

```ts
export default {
  title: 'Greeter',
  component: Greeter,
  argTypes: {
    new: {
      control: 'boolean',
    },
  },
};

export const story = (args) => defineComponent({
  components: {
    Greeter, // The component above ^.
  },
  setup() {
    useMockRoute({
      meta: {
        new: args.new,
      },
    });
  },
  template: `
    <Greeter />
  `,
});
```

Notably, for nearly all components setting up an entire router is overkill. I only want to insert the little bit that the component actually uses.

There are some components that use the router, and for those I would request a `useMockRouter` hook that doesn't so much set the routes for the story as it intercepts and logs the parameters to any of the methods.

The use case this library currently implements is extremely useful for the case where you want to boot up the whole app with a subset of routes, but those components are actually quite rare. Small apps would only have just one such story, specifically the one that boots up the entire app in Storybook.

Does that help at all?

**Comment by NickMcBurney** [comment]
Yes thats great thanks, will provide update ASAP.

**Comment by NickMcBurney** [comment]
@misha I've created a [new PR](https://github.com/NickMcBurney/storybook-vue3-router/pull/18), with this I had added a new decorator `mockRouter` which allows for simple mocked `$route` and `$router`, you can see preview storybook build here: https://deploy-preview-18--storybook-vue3-router.netlify.app/?path=/story/mock-router--default (have a look at the dynamic template story as this replicates your suggestion)

I don't think i'm going to be able to mock `useRoute` or `useRouter` as within your components these would be imported from `vue-router` and require the `vue-router` is initalised.

I'll keep looking into this though and see if I can find a way.

Thanks for your feedback this has been a good addition to the package and you're completely correct that many people may not require the full router setup so the mocked version is a nice alternative.

**Comment by NickMcBurney** [comment]
@misha I've completed the PR linked above - adding a mockRouter to the package.

Closing issue
