### ISSUE TITLE
storybook-vue3-router doesn't appear to be written in CJS

### ISSUE THREAD

**Issue by olemarius** [NickMcBurney/storybook-vue3-router#19]
I get this warning, using storybook with vite

storybook-vue3-router doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.

**Comment by NickMcBurney** [comment]
@olemarius there was an [issue ](#1) with a very early version of the package not exposing entry point correctly, but this was resolved with version 1.0.1, can you confirm you're using higher version?

I've just created a new Vite app and installed package and it worked as expected, if you are using v1.0.1+ would it be possible for you to provide reproduction?

**Comment by NickMcBurney** [comment]
@olemarius I've published a new version which should now work for you: v2.2.1
