### ISSUE TITLE
Can not install the latest version with @storybook/vue3:6.5.0-alpha

### ISSUE THREAD

**Issue by khangvo88** [NickMcBurney/storybook-vue3-router#21]
I current use the `@storybook/vue3:6.5.0-alpha.4`. When I run `npm install --save-dev storybook-vue3-router`

it prompts an error: 

```
Could not resolve dependency:
error peer @storybook/vue3@"6.x" from storybook-vue3-router@2.2.1
```

I would be nice if that package support latest version of storybook/vue3

**Comment by NickMcBurney** [comment]
@khangvo88 I think this is because version 6.5.0 is not released yet (its still on alpha) so npm's peer dependency check fails.

Running `npm install storybook-vue3-router --force` may work and once 6.5.0 is officially released ill check support properly.

**Comment by nick-barth** [comment]
Just forced it with `^6.5.0-alpha.21` and it worked.  Thanks for the package.
