### ISSUE TITLE
Support the useLink composable

### ISSUE THREAD

**Issue by soutoigor** [NickMcBurney/storybook-vue3-router#23]
Now with Vue 3 it's common that we use the [`useLink` composable](https://router.vuejs.org/guide/advanced/composition-api.html#uselink)., and currently it's not being supported by the addon.

The errors:
`[Vue warn]: injection "Symbol([vue-router]: route location)" not found. `
and
`TypeError: Cannot read properties of undefined (reading 'resolve')`
are given.

**Comment by NickMcBurney** [comment]
@soutoigor can you provide a repo link? 

I've tested this and it seems to be working as expected:

- Component with [`useLink`](https://github.com/NickMcBurney/storybook-vue3-router/blob/useLink/examples/components/appLink.vue)
- Story [code](https://github.com/NickMcBurney/storybook-vue3-router/blob/useLink/examples/appLink.stories.ts)
- Preview [Storybook build](https://deploy-preview-25--storybook-vue3-router.netlify.app/?path=/story/router-link--default)

The error you're getting seems to be related to it looking for a route which is not defined, have you setup the [custom route options](https://github.com/NickMcBurney/storybook-vue3-router/tree/main#custom-routes) as shown in readme?

**Comment by NickMcBurney** [comment]
@soutoigor I'll close issue if I dont hear back from you within the next week, please let me know if you're still having issues.

**Comment by NickMcBurney** [comment]
Closed due to inactivity and lack of reproduction details.
