### ISSUE TITLE
`mockRouter` not compatible with `useRouter`

### ISSUE THREAD

**Issue by pietdevries94** [NickMcBurney/storybook-vue3-router#26]
When trying to mock the router, while navigating using `useRouter` in my script, it throws the following error.

```
router is undefined

nav@http://localhost:6006/src/storybook/helpers/Test.vue?t=1657695992104:9:7
callWithErrorHandling@http://localhost:6006/node_modules/.vite-storybook/deps/chunk-BQRQI6EQ.js?v=e70b3dd4:1428:18
callWithAsyncErrorHandling@http://localhost:6006/node_modules/.vite-storybook/deps/chunk-BQRQI6EQ.js?v=e70b3dd4:1436:38
invoker@http://localhost:6006/node_modules/.vite-storybook/deps/chunk-BQRQI6EQ.js?v=e70b3dd4:7645:33
```

This error can be reproduced with the following component and story.

`Test.vue`
```vue
<script lang="ts" setup>
import { useRouter } from "vue-router";

const router = useRouter();

function nav() {
  router.push({ name: "dummy" });
}
</script>

<template>
  <button @click="nav">Navigate</button>
</template>

```

`Test.strories.ts`
```ts
import { StoryFn } from "@storybook/vue3";
import { mockRouter } from "storybook-vue3-router";
import Test from "./Test.vue";

export default {
  component: Test,
};

const Template: StoryFn = () => ({
  components: { Test },
  template: `<Test />`,
});

export const Default = Template.bind({});
Default.decorators = [mockRouter({})];
```

**Comment by NickMcBurney** [comment]
@pietdevries94 the mock router is not intended for use like this. But using the full router implementation does work with `useRouter`. Is there a reason you wanted to use `mockRouter` decorator?

**Comment by pietdevries94** [comment]
@NickMcBurney Good to know it's not a bug, but a limitation. I wanted to use it to isolate some tests, based on stories, which I write using the play interactions. I now just give them a simple router in which the guard contains a jest spy with the data and abort . Wrapped it in a helper function and it now behaves exactly as needed. :) Thanks for the response!
