### ISSUE TITLE
how does one predefine useRoute().path for storybook item?

### ISSUE THREAD

**Issue by iambumblehead** [NickMcBurney/storybook-vue3-router#28]
I'm using a component like this one...
```js
import { useRoute } from 'vue-router';
import { storeToRefs } from 'pinia';

export default {
  template: `<div>the template's route path {{ routePath }}</div>`,
  setup () {
    const route = storeToRefs(useRoute());
    const routePath = route.path;
    console.log('ROUTE', route.path); // ROUTE undefined
    return { routePath };
  }
}
```

and the associated stories.js file mounts the component using storybook-vue3-router with these options
```js
NORMAL.decorators = [vueRouter([], {
  initialRoute: '/test',
  path: '/test'
})];
```

Am I doing something wrong? How does one define the router path for a component like this?

**Comment by NickMcBurney** [comment]
I think the issue is how your adding the decorator, you're passing an empty array of routes which at best will use the default routes (which doesn't include a /test route) and worst will not provide router with any routes to use.

If you want to use a custom starting route then you need to provide the routes/components for this.

Does it not work if you just use
```
NORMAL.decorators = [vueRouter()];
```

With that I'd expect `route.path` to be `'home'`

**Comment by iambumblehead** [comment]
```js
NORMAL.decorators = [vueRouter()];
```
using the above decorator, route.path is undefined

**Comment by iambumblehead** [comment]
probably a demo app would be needed to show the issue more effectively, but I don't have time now to make a demo

**Comment by NickMcBurney** [comment]
Ok, I've not tried this with Pina so wonder if something is going wrong when passing `storeToRefs(useRoute())`

If you can provide a demo/reproduction that would be very helpful. I'll also try to but unlikely to be until the weekend at the earliest.

**Comment by iambumblehead** [comment]
useRoute() returns `undefined`

**Comment by NickMcBurney** [comment]
That's strange, `useRoute` definitely works in the examples I have, I suspect there must be some issue with your implementation, but if your using the default `vueRouter()` setup then I'm not sure what would cause this. If you can provide a demo this would help me debug the issue.

**Comment by iambumblehead** [comment]
I took another quick look just now and believe to have found the problem and will explain.

The files I'm using look like this. Basically, storybook is not included in the project root but is instead found in a sub-directory. In a past experience, storybook's chaotic interface, version and plugin changes made another project difficult to work with, so for this project storybook is configured and contained in a separated place.
```console
example-project
├── package.json
└── storybook
    └── package.json
```
both the" example-project" and "storybook node_modules" files have a "vue-router" package. Deleting "storybook/node_modules/vue-router" seems to have resolved the issue. I'm looking for a way to continue keeping storybook in a separated place while, at the same time, using the root project's node_modules/vue-router package from within storybook

**Comment by iambumblehead** [comment]
a solution is to define this vue-router dependency inside "storybook/package.json"
```diff
+    "vue-router": "../node_modules/vue-router"
```
this solution would not work in a win32 environment but I am not using win32 so all is fine here
