### ISSUE TITLE
how does use url params? is this a bug?

### ISSUE THREAD

**Issue by iambumblehead** [NickMcBurney/storybook-vue3-router#29]
I have a route path like this `'/s-:name/assets/'` and am using storybook-vue3-router in the following way
```javascript
NORMAL.decorators = [vueRouter(routes, {
  initialRoute: '/s-myname/assets/'
})];
```

inside the component's setup function, this params value is undefind. When the app is used normally, this value is defined "myname",
```javascript
const route = storeToRefs(useRoute());
console.log( 'NAME', route.params.value.name ); // NAME undefined
```

thanks for any response you may give

**Comment by iambumblehead** [comment]
this appears in the browser console,
```console
[Vue Router warn]: No match found for location with path "/s-myname/assets/"
```

**Comment by NickMcBurney** [comment]
I do have an example which user router props here https://github.com/NickMcBurney/storybook-vue3-router/blob/main/examples/withRouterProps.stories.ts

But I've not tried implementing in the same way you have (where the prop is prefixed e.g. `/static-:prop/sub-route`)

I can try looking into this for you at the weekend, but this decorator makes use of vue-router and as this is using Vue router props I would have expected it to already work.

**Comment by NickMcBurney** [comment]
In your `routes` var where you define routes for the decorator, have you included the child route for `/assets/` the console error you indicates it can't find the route and this could be why.

**Comment by iambumblehead** [comment]
when I first opened this issue, the route definitions weren't being passed correctly and so there was a console message showing that a matching route could not be found, but after changing the route definition the console error stopped appearing.

it would be great if you would take a look at a time that is convenient for you

**Comment by NickMcBurney** [comment]
Hi I've looked into this and been able to create a working example, you can see my PR here: https://github.com/NickMcBurney/storybook-vue3-router/pull/30 which adds an example of prefixing route with '@' (e.g. for username).

There is also a preview link for the example here: https://deploy-preview-30--storybook-vue3-router.netlify.app/?path=/story/router-props--username-prefix 
If you click the 'User: @nick' link you will see the username prop of 'nick' is passed into the component

You can also click the 'User Details' link to see a nested link working with router - along with the full path displayed at the top.

I think the issue must be in your code, rather than my decorator. If you can provide full code example I'm happy to do a quick review and see if I can spot anything.

**Comment by iambumblehead** [comment]
@NickMcBurney thank you for the amazing support. I'll take a look soon and, if I can't get things working, I'll make a full code example

**Comment by iambumblehead** [comment]
I would note that none of the changes referred to use initialRoute or a path like this one in the original comment, but the changes are still appreciated

**Comment by NickMcBurney** [comment]
Yeah I missed this, I've just confirmed this is working for me too and I've pushed this change (will be on that preview link in a few mins)

**Comment by iambumblehead** [comment]
thanks for your support. the process of making a demonstration version revealed a problem in my sources.

if the issue does originate from storybook-vue3-router, I wil complete the demo project and provide a link here
if the issue does not originate from storybook-vue3-router, I will mark this discussion closed

it is assumed these actions will be agreeable to you :)

**Comment by iambumblehead** [comment]
I apologize for inconveniencing you with this ticket -- closing

**Comment by NickMcBurney** [comment]
> I apologize for inconveniencing you with this ticket -- closing

No problem at all, I'm glad you were able to resolve the issue 🙂
