### ISSUE TITLE
v3 - setup can only be called once

### ISSUE THREAD

**Issue by callumacrae** [NickMcBurney/storybook-vue3-router#46]
Hey! Good work on this plugin, it seems like it'll be super useful :)

https://github.com/NickMcBurney/storybook-vue3-router/blob/bd10c17ccc9320687a5cbc15ebc2a95b1227ee5d/src/withVueRouter.ts#L47

This breaks my storybook setup as I'm using the setup function in `preview.js`.

`setup` can only be called once - https://github.com/storybookjs/storybook/issues/20579

**Comment by callumacrae** [comment]
looks like this might not be a problem in a future version of storybook! https://github.com/storybookjs/storybook/pull/22170

**Comment by NickMcBurney** [comment]
This was resolved by Storybook and you can use this package with Storybook@7 using version 3+
