### ISSUE TITLE
Icon not displayed

### ISSUE THREAD

**Issue by zic-liu** [NickMcBurney/storybook-vue3-router#50]
I introduced the icon via setup in **preview.js**: 
```
import * as ElementPlusIconVue from '@element-plus/icons-vue'

setup((app) => {
    for(const [key, component] of Object.entries(ElementPlusIconVue)) {
       app.component(key, component)
    }
})
```

But when I use router in the component, the icons of the page are not displayed; 
if I introduce the icons and el-icon separately in the page, the icons are showed.

**Comment by NickMcBurney** [comment]
Can you provide a reproduction repo which I can try out on?

**Comment by zic-liu** [comment]
> Can you provide a reproduction repo which I can try out on?

I had updated storybook, then I solved the problem, thanks!
